spring.data.mongodb.host=127.0.0.1
spring.data.mongodb.port=27017
spring.data.mongodb.authentication-database=admin
spring.data.mongodb.username=AdminHawk
spring.data.mongodb.password=Y3ll0w39!
spring.data.mongodb.database=blogposts